### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by ashvin-zwt** [zealousweb/accept-authorize-net-payments-using-contact-form-7#2]
Hello Team,
While clicking on the submit button after filling in the basic details payment form is showing but the page not scrolling to the start of the payment form. It stays in the same position when it is.

Thank You!

**Comment by Cristopher2511** [comment]
Hi @ashvin-zwt 

We have change this scenario and remove scrolling after payment. Because now CF7 for and Credit card Form both are showing on single Page. So after payment not required to scroll. 
So once try version 1.8 of free version if you have any issue you can generate issue here agian, or reopen it. For now going to close this issue.

Thanks,
